### ISSUE TITLE
parser.watch() uses a callback versus synthetic events

### ISSUE THREAD

**Issue by kitsonk** [dojo/parser#1]
When implementing the proposal, it seemed better to utilise an optional callback for notifying of objects that were instantiated/dereferenced than to utilise synthetic events captured via some sort of `on` syntax.  This does lead down a "slippery" slope of potential inconsistencies.  Thoughts?

**Comment by mwistrand** [comment]
Considering that `watch` is more or less a parser-specific wrapper around `MutationObserver`, using a single callback makes sense. Even if an event system were desired, I'm not sure which events would be listened to/emitted, apart from inspecting each `MutationRecord` object. So I don't see `dojo-core/Evented` being used here. If we were to expose an API to add any number of callbacks, it would need to provide mechanisms for adding/removing callbacks as well as starting/stopping the observer:

```ts
class ParserObserver {
	constructor(node?: HTMLElement) {}
	addListener(): Handle {}
	start(): void {}
	stop(): void {}
}
```

**Comment by maier49** [comment]
I tend to agree with @mwistrand 's point about `MutationObserver`. if the prevailing wisdom is to move away from events for this kind of thing to a callback based design I think the default decision would be to follow suit, unless the slope of potential inconsistencies does turn out to be particularly slippery.

**Comment by kitsonk** [comment]
@dylans talked about this.  He challenged on several aspects and I don't know if he was just playing devil's advocate, but I cannot see a situation where you would be able to hold up the event paradigm and deliver several

I agree with the "prevailing wisdom" too.  Clearly though, prevailing wisdom is being entirely inconsistent. Promise/Generators/async/await/events/topics/event busses/[CSP](http://phuu.net/2014/08/31/csp-and-transducers.html)...

@mwistrand currently if you watch, you get a handle, which allows you to remove the callback.  What you are suggesting is more of an event hub/bus, which I am suspecting is going to be needed eventually for Dojo 2, something where the sender and the receiver are loosely coupled, but there can be more rich functionality about how information is delivered, including a level of filtering, pausability, etc.  I would hate to build something rich like that only for .watch().  While we have topics in Dojo 1 they aren't that feature rich. Thinking out loud, I could see two main solutions to problems of communication between objects for Dojo 2:

* Where the sender and receiver are tightly coupled together and there is a one to one relationship between sender and receiver, and the message to be sent fits the "event" model, events.
* Where there are messages, where the sender and receiver do not want to be tightly coupled, where there is a need for listeners to "glob" message types, where there is a need to queue, reorder, prioritise, or invalidate messages and the message format does not fit the "event" model, then this new "hub" model.

Does that make any sense?

**Comment by kitsonk** [comment]
When we revisit this, it actually should be ES `Observable` that we use as the `.watch()` interface.

**Comment by kitsonk** [comment]
On the other hand, discussion around app with @novemberborn indicates that we might not want this feature...
