### ISSUE TITLE
Parser Objects versus Compose Objects

### ISSUE THREAD

**Issue by kitsonk** [dojo/parser#3]
The parser proposal indicates that the API signature of a parser class would be something like this:

```typescript
interface ParserObject {
    node: HTMLElement;
    id: string;
    [name: string]: any;
}

interface ParserConstructor<T extends ParserObject, O> {
    new (node: HTMLElement, options?: O): T;
}
```

While the compose proposal follows the following:

```typescript
interface ComposeConstructor {
  new (options?: any): any;
}
```

In order to make the API consistent, it maybe better to change the parser proposal to something like this:

```typescript
interface ParserConstructorOptions {
    node: HTMLElement;
    [option: string]: any;
}

interface ParserObject {
    node: HTMLElement;
    id: string;
    [name: string]: any;
}

interface ParserConstructor<T extends ParserObject, O extends ParserConstructorOptions> {
    new (options?: O): T;
}
```

In this case only a single `options` argument is passed on object instantiation, which would have a mandatory `node` property.

**Comment by jdonaghue** [comment]
The only issue that I see is that in the original definition a ```node``` is required to be passed into the constructor but with the modification that you are presenting a ```node``` is only required if ```options``` were to be passed in. ```options``` are optional in the interface definition so one could get away without passing in anything. If we removed the '?' on ```options``` your intentions should be satisfied though. Besides that I think this makes a lot of sense in terms of api consistency.

The only other downside that I can see is that if someone were to not want to pass in any options, this still requires them to construct an object that contains the node, whereas with the old definition they could simply pass the node in as a single argument. This seems to be a relatively trivial point though and the benefits of api consistency probably outweigh it.

**Comment by jdonaghue** [comment]
However, in the current implementation https://github.com/dojo/parser/blob/master/src/parser.ts#L16 ```node``` is optional in the constructor. If this is the desired behavior then disregard my previous comments. It seems like it should be required though, so I am wondering if this is a bug in the current implementation?

**Comment by maier49** [comment]
After looking over the parser proposal and code for a bit, I agree with @jdonaghue 's assessment. I also just wanted to point out that the proposal also lists `node` as optional in `ParserObjectConstructor`, so if that was a mistake we may want to update it there as well.

**Comment by kitsonk** [comment]
@jdonaghue it isn't intended as a mistake in the implementation.  My logic, while maybe flawed, was that while the parser would always know a node to pass the constructor, if you wanted to construct something that was "compatible" with the parser but was not yet inserted into the DOM, how would you know the DOM node?  Maybe my thinking is flawed... hmmmm...

**Comment by bitpshr** [comment]
@kitsonk, do you have a specific use case for the situation you're describing? The way I see it, one should only ever care about parser compatibility when actually using it to parse something, in which case, as you mentioned, a node will always be known.

**Comment by kitsonk** [comment]
@bitpshr as a general point of principal, a constructor should have a default behaviour if it isn't given any options.  For example in the case of a widget, if it isn't expressly given a node, it should create itself a node on the current document and then if you have a method attaching it, it would use that node for its insertion (or it should not create the node until it is being inserted into the DOM and is either given a node at that point or creates one to insert itself.

**Comment by kitsonk** [comment]
Since this package is likely to be retired, will close this.
