### ISSUE TITLE
Parser should account for multiple documents and throw error when ID already registered.

### ISSUE THREAD

**Issue by mwistrand** [dojo/parser#4]
Note that the following concerns https://github.com/dojo/parser/blob/master/src/parser.ts#L77-L79. Considering that the parser accounts for multiple documents simultaneously, the `idMap` should as well, especially since node IDs are only supposed to be unique on a per-document basis. As for IDs that have already been registered within a single document, I'm inclined to believe an error should be thrown. Otherwise users might get into trouble without an immediate indication of the problem. For example, consider the following scenario:

```html
<div id="root">
	<p id="child"></p>
</div>
```

```ts
const root = document.getElementById('root');
watch({
	root: root
});

const oldChild = document.getElementById('child');
const newChild = document.createElement('div');
newChild.id = 'child';

root.insertBefore(newChild, oldChild);
root.removeChild(oldChild);
```

Since the new node is added before the old node is removed, `instantiateParserObject` will try to add the new instance to the `idMap` before the old one has been removed. As a result, `byNode(newChild)` will work, but `byId(newChild.id)` will not.

**Comment by kitsonk** [comment]
Yes, I am not 100% sure I had multi-document handling done fully as well as what to do about duplicate IDs... glad you picked up on it.
